/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Address struct {

	City string `json:"city,omitempty"`

	Country string `json:"country,omitempty"`

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	PostalCode string `json:"postalCode,omitempty"`

	StateProvince string `json:"stateProvince,omitempty"`

	StreetAddress string `json:"streetAddress,omitempty"`
}
