/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Authorization struct {

	ServiceId int64 `json:"serviceId,omitempty"`

	ServiceUserId string `json:"serviceUserId,omitempty"`
}
