/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Cancellation struct {

	CancellationType string `json:"cancellationType,omitempty"`

	SubscriptionId int64 `json:"subscriptionId,omitempty"`
}
