/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ChargingLog struct {

	AppliedCoupon int64 `json:"appliedCoupon,omitempty"`

	AuthCode string `json:"authCode,omitempty"`

	CompanyId int64 `json:"companyId,omitempty"`

	CreateDate time.Time `json:"createDate,omitempty"`

	Currency string `json:"currency,omitempty"`

	ErrorCode string `json:"errorCode,omitempty"`

	ErrorText string `json:"errorText,omitempty"`

	Id int64 `json:"id,omitempty"`

	InvoiceId int64 `json:"invoiceId,omitempty"`

	JobId int64 `json:"jobId,omitempty"`

	Parent *ChargingLog `json:"parent,omitempty"`

	PaymentGateway string `json:"paymentGateway,omitempty"`

	PaymentId string `json:"paymentId,omitempty"`

	Price float32 `json:"price,omitempty"`

	Reason string `json:"reason,omitempty"`

	ServiceInstanceId int64 `json:"serviceInstanceId,omitempty"`

	Status string `json:"status,omitempty"`

	SubscriberSecureId string `json:"subscriberSecureId,omitempty"`

	SubscriptionId int64 `json:"subscriptionId,omitempty"`

	TransactionId string `json:"transactionId,omitempty"`
}
