/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Company struct {

	Address *Address `json:"address,omitempty"`

	Id int64 `json:"id,omitempty"`

	Name string `json:"name"`
}
