/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Coupon struct {

	Code string `json:"code,omitempty"`

	Company *Company `json:"company,omitempty"`

	CurrentUsage int32 `json:"currentUsage,omitempty"`

	DiscountAmount float32 `json:"discountAmount"`

	DiscountType string `json:"discountType"`

	ExpireDate time.Time `json:"expireDate,omitempty"`

	Id int64 `json:"id,omitempty"`

	MaxLimit int32 `json:"maxLimit"`
}
