/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Deduction struct {

	Amount int64 `json:"amount,omitempty"`

	Id int64 `json:"id,omitempty"`

	ServiceId int64 `json:"serviceId,omitempty"`

	UsageEndTime time.Time `json:"usageEndTime,omitempty"`

	UsageStartTime time.Time `json:"usageStartTime,omitempty"`

	UserId string `json:"userId,omitempty"`
}
