/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type InvoiceRequest struct {

	CustomerId int64 `json:"customerId,omitempty"`

	SelectedDate time.Time `json:"selectedDate,omitempty"`

	ServiceUserId int64 `json:"serviceUserId,omitempty"`
}
