/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MessageTemplate struct {

	Company *Company `json:"company"`

	Enabled bool `json:"enabled,omitempty"`

	EventType string `json:"eventType,omitempty"`

	Id int64 `json:"id,omitempty"`

	MessageTemplate string `json:"messageTemplate,omitempty"`

	NotificationType string `json:"notificationType,omitempty"`

	Sender string `json:"sender,omitempty"`

	Subject string `json:"subject,omitempty"`
}
