/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Offer struct {

	Company *Company `json:"company"`

	Id int64 `json:"id,omitempty"`

	Name string `json:"name"`

	OpenEnded bool `json:"openEnded"`

	Price float32 `json:"price"`

	Recurrence *RecurrencePeriod `json:"recurrence"`

	RecurrenceCount int32 `json:"recurrenceCount,omitempty"`

	SecureId string `json:"secureId,omitempty"`

	TrialPeriod int32 `json:"trialPeriod,omitempty"`
}
