/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PaymentCard struct {

	CardAlias string `json:"cardAlias,omitempty"`

	CardExpiry string `json:"cardExpiry,omitempty"`

	CardHolderName string `json:"cardHolderName,omitempty"`

	CardNumber string `json:"cardNumber,omitempty"`

	CardToken string `json:"cardToken,omitempty"`

	CardUserKey string `json:"cardUserKey,omitempty"`

	Cvc string `json:"cvc,omitempty"`

	ExpireMonth string `json:"expireMonth,omitempty"`

	ExpireYear string `json:"expireYear,omitempty"`

	RegisterCard int32 `json:"registerCard,omitempty"`
}
