/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProfileInfoVm struct {

	ActiveProfiles []string `json:"activeProfiles,omitempty"`

	RibbonEnv string `json:"ribbonEnv,omitempty"`
}
