/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RecurrencePeriod struct {

	Id int64 `json:"id,omitempty"`

	Length int64 `json:"length"`

	RecurrenceType string `json:"recurrenceType"`
}
