/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponseEntity struct {

	Body *interface{} `json:"body,omitempty"`

	StatusCode string `json:"statusCode,omitempty"`

	StatusCodeValue int32 `json:"statusCodeValue,omitempty"`
}
