/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SavedCard struct {

	BinNumber string `json:"binNumber,omitempty"`

	CardAlias string `json:"cardAlias,omitempty"`

	CardAssociation string `json:"cardAssociation,omitempty"`

	CardBankCode int64 `json:"cardBankCode,omitempty"`

	CardBankName string `json:"cardBankName,omitempty"`

	CardFamily string `json:"cardFamily,omitempty"`

	CardToken string `json:"cardToken,omitempty"`

	CardUserKey string `json:"cardUserKey,omitempty"`

	CartType string `json:"cartType,omitempty"`

	Id int64 `json:"id,omitempty"`
}
