/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Service struct {

	Company *Company `json:"company"`

	Id int64 `json:"id,omitempty"`

	Name string `json:"name"`

	Type_ string `json:"type"`
}
