/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ServiceOffering struct {

	Company *Company `json:"company,omitempty"`

	Description string `json:"description,omitempty"`

	Id int64 `json:"id,omitempty"`

	Offer *Offer `json:"offer"`

	OverUsagePrice float32 `json:"overUsagePrice,omitempty"`

	OverUsageQuota float32 `json:"overUsageQuota,omitempty"`

	Price float32 `json:"price,omitempty"`

	QuotaAmount float32 `json:"quotaAmount"`

	Service *Service `json:"service,omitempty"`

	UnitName string `json:"unitName,omitempty"`
}
