/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Subscriber struct {

	Address string `json:"address,omitempty"`

	City string `json:"city,omitempty"`

	Country string `json:"country,omitempty"`

	Email string `json:"email,omitempty"`

	GsmNumber string `json:"gsmNumber,omitempty"`

	IdentityNumber string `json:"identityNumber,omitempty"`

	Ip string `json:"ip,omitempty"`

	LastLoginDate string `json:"lastLoginDate,omitempty"`

	Name string `json:"name,omitempty"`

	RegistrationDate string `json:"registrationDate,omitempty"`

	SecureId string `json:"secureId,omitempty"`

	ShippingAddress string `json:"shippingAddress,omitempty"`

	ShippingCity string `json:"shippingCity,omitempty"`

	ShippingCountry string `json:"shippingCountry,omitempty"`

	ShippingName string `json:"shippingName,omitempty"`

	ShippingZipCode string `json:"shippingZipCode,omitempty"`

	Surname string `json:"surname,omitempty"`

	UseBillingAddressForShipping bool `json:"useBillingAddressForShipping,omitempty"`

	ZipCode string `json:"zipCode,omitempty"`
}
