/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Subsription struct {

	AppliedCoupon *Coupon `json:"appliedCoupon,omitempty"`

	CancelDate time.Time `json:"cancelDate,omitempty"`

	Card *SavedCard `json:"card,omitempty"`

	Company *Company `json:"company"`

	EndDate time.Time `json:"endDate,omitempty"`

	Id int64 `json:"id,omitempty"`

	NextChargingDate time.Time `json:"nextChargingDate,omitempty"`

	Offer *Offer `json:"offer"`

	Services []ServiceInstance `json:"services,omitempty"`

	StartDate time.Time `json:"startDate,omitempty"`

	Status string `json:"status,omitempty"`

	SubscriberId string `json:"subscriberId,omitempty"`

	Version int64 `json:"version,omitempty"`
}
