/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type User struct {

	Activated bool `json:"activated"`

	Authorities []Authority `json:"authorities,omitempty"`

	Company *Company `json:"company,omitempty"`

	CreatedDate time.Time `json:"createdDate,omitempty"`

	Email string `json:"email,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	Id int64 `json:"id,omitempty"`

	ImageUrl string `json:"imageUrl,omitempty"`

	LangKey string `json:"langKey,omitempty"`

	LastModifiedDate time.Time `json:"lastModifiedDate,omitempty"`

	LastName string `json:"lastName,omitempty"`

	Login string `json:"login"`

	ResetDate time.Time `json:"resetDate,omitempty"`
}
